#pragma config(Sensor, in1,    armPot,         sensorPotentiometer)
#pragma config(Motor,  port2,           rightDrive,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftDrive,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           leftSpinner,   tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           rightSpinner,  tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           leftArm,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           rightArm,      tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"

#include "user_control.c"

void pre_autonomous() {
 
}

task autonomous() {
	
}

task usercontrol() {
	userControlLoop();
}