#pragma config(Sensor, in1,		 shoulder1,			 sensorPotentiometer)
#pragma config(Motor,	 port1,						frontLeft,		 tmotorVex269, openLoop, reversed)
#pragma config(Motor,	 port3,						backLeft,			 tmotorVex269, openLoop)
#pragma config(Motor,	 port4,						arm1,					 tmotorVex393, openLoop, reversed)
#pragma config(Motor,	 port5,						arm2,					 tmotorVex393, openLoop)
#pragma config(Motor,	 port6,						spinner1,			 tmotorVex393, openLoop)
#pragma config(Motor,	 port7,						spinner2,			 tmotorVex393, openLoop, reversed)
#pragma config(Motor,	 port9,						backRight,		 tmotorVex269, openLoop, reversed)
#pragma config(Motor,	 port10,					frontRight,		 tmotorVex269, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

//*Code generated by Connor Egbert because he is amazing							 *//

task main()
{
	while(true)
	{
		motor[frontRight] = vexRT[Ch2];
		motor[frontLeft] = vexRT[Ch3];
		motor[backRight] = vexRT[Ch2];
		motor[backLeft] = vexRT[Ch3];
		motor[spinner1] = vexRT[Ch3Xmtr2];
		motor[spinner2] = vexRT[Ch3Xmtr2];

		if(SensorValue[shoulder1] > 2150)
		{
			motor[arm1] = vexRT[Ch2Xmtr2] - 10;
			motor[arm2] = vexRT[Ch2Xmtr2] - 10;
		}

		else
		{
			motor[arm1] = vexRT[Ch2Xmtr2];
			motor[arm2] = vexRT[Ch2Xmtr2];
		}
	}
}
