#pragma config(Sensor, in1,    armPot,         sensorPotentiometer)
#pragma config(Motor,  port2,           leftDrive,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightDrive,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           leftSpinner,   tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           rightSpinner,  tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           leftArm,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           rightArm,      tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define MAX_PWR  127
#define HALF_PWR MAX_PWR / 2

#include "user_control.c"

task main() {
	userControlLoop();
}
