#pragma config(Sensor, in2,    gyro,           sensorGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "GyroLib.c"

task main() {
  GyroInit(gyro);
  
  while (true)
    wait1Msec(1000);
}
