#pragma config(Sensor, in1,    armPot,         sensorPotentiometer)
#pragma config(Motor,  port2,           leftDrive,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightDrive,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           leftSpinner,   tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           rightSpinner,  tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           leftArm,       tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port7,           rightArm,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drive.c"
#include "spinners.c"
#include "arm.c"

task main() {
	while (true) {
		updateSpinners();
		updateDrive();
		updateArm();
	}
}
