#pragma config(Sensor, in1,    armPot,         sensorPotentiometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int val = 0;

task main()
{
	while (true) {
		val = SensorValue[armPot];
	}
}
