#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    armPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl3,  leftFrontDrive, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rightFrontDrive, sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  rightBackDriveEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  leftBackDriveEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           backLeftDrive, tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port3,           frontLeftDrive, tmotorVex393HighSpeed, openLoop, encoder, encoderPort, dgtl3, 1000)
#pragma config(Motor,  port4,           leftArm,       tmotorVex393, openLoop)
#pragma config(Motor,  port5,           leftIntake,    tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port6,           backRightDrive, tmotorVex393HighSpeed, openLoop, reversed, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port7,           frontRightDrive, tmotorVex393HighSpeed, openLoop, reversed, encoder, encoderPort, dgtl5, 1000)
#pragma config(Motor,  port8,           rightArm,      tmotorVex393, openLoop)
#pragma config(Motor,  port9,           rightIntake,   tmotorVex393HighSpeed, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "tuning.c"

#define HIGH_SPEED_AND_IME 392.0
#define RED_ENCODER 360.0

task main() {
  fillMotorSpeedsArrWithUnadjusted(backRightDrive, HIGH_SPEED_AND_IME);

  wait1Msec(1000);

  writeDebugStreamLine("Unadjusted motor speed data:");
  printMotorSpeedsGraphable();

  fillMotorSettingLut();
  fillMotorSpeedsArrWithAdjusted(backRightDrive, HIGH_SPEED_AND_IME);

  wait1Msec(1000);

  writeDebugStreamLine("Adjusted motor speed data:");
  printMotorSpeedsGraphable();

  printSettingLut();
}
